version: '3.8'

services:
  partner-management:
    environment:
      - DATABASE_URL=postgresql://hexabuilders_user:hexabuilders_password@host.docker.internal:5432/hexabuilders
      - PULSAR_BROKER_URL=pulsar://localhost:6650
      - PULSAR_ADMIN_URL=http://localhost:8080

  onboarding:
    environment:
      - DATABASE_URL=postgresql://hexabuilders_user:hexabuilders_password@host.docker.internal:5432/hexabuilders
      - PULSAR_BROKER_URL=pulsar://localhost:6650
      - PULSAR_ADMIN_URL=http://localhost:8080

  recruitment:
    environment:
      - DATABASE_URL=postgresql://hexabuilders_user:hexabuilders_password@host.docker.internal:5432/hexabuilders
      - ELASTICSEARCH_URL=http://localhost:9200
      - PULSAR_BROKER_URL=pulsar://localhost:6650
      - PULSAR_ADMIN_URL=http://localhost:8080

  campaign-management:
    environment:
      - DATABASE_URL=postgresql://hexabuilders_user:hexabuilders_password@host.docker.internal:5432/hexabuilders
      - PULSAR_BROKER_URL=pulsar://localhost:6650
      - PULSAR_ADMIN_URL=http://localhost:8080