apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-web
  namespace: hexabuilders
  labels:
    app: bff-web
    component: api-gateway
spec:
  replicas: 2  # Multiple replicas for high availability
  selector:
    matchLabels:
      app: bff-web
  template:
    metadata:
      labels:
        app: bff-web
        component: api-gateway
    spec:
      containers:
      - name: bff-web
        image: gcr.io/PROJECT_ID/hexabuilders-bff-web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: PYTHONPATH
          value: "/app/src"
        - name: SAGA_SERVICE_URL
          value: "http://partner-management:5000"
        - name: SAGA_SERVICE_TIMEOUT
          value: "30"
        - name: BFF_PORT
          value: "8000"
        - name: ENVIRONMENT
          value: "production"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: bff-web
  namespace: hexabuilders
  labels:
    app: bff-web
    component: api-gateway
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  selector:
    app: bff-web
---
# LoadBalancer service para acceso externo
apiVersion: v1
kind: Service
metadata:
  name: bff-web-lb
  namespace: hexabuilders
  labels:
    app: bff-web
    component: loadbalancer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    name: http
  selector:
    app: bff-web
