apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: hexabuilders
  labels:
    app: zookeeper
    component: pulsar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
        component: pulsar
    spec:
      containers:
      - name: zookeeper
        image: apachepulsar/pulsar:3.1.0
        ports:
        - containerPort: 2181
          name: client
        env:
        - name: metadataStoreUrl
          value: "zk:zookeeper:2181"
        - name: PULSAR_MEM
          value: "-Xms256m -Xmx256m -XX:MaxDirectMemorySize=256m"
        command:
        - bash
        - -c
        - |
          bin/apply-config-from-env.py conf/zookeeper.conf && \
          bin/generate-zookeeper-config.sh conf/zookeeper.conf && \
          exec bin/pulsar zookeeper
        volumeMounts:
        - name: zk-data
          mountPath: /pulsar/data
        - name: zk-conf
          mountPath: /pulsar/conf
        livenessProbe:
          exec:
            command:
              - bin/pulsar-zookeeper-ruok.sh
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - bin/pulsar-zookeeper-ruok.sh
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: zk-data
        emptyDir: {}
      - name: zk-conf
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: hexabuilders
  labels:
    app: zookeeper
    component: pulsar
spec:
  ports:
  - port: 2181
    targetPort: 2181
    name: client
  selector:
    app: zookeeper
