apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: hexabuilders
  labels:
    app: zookeeper
    component: pulsar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
        component: pulsar
    spec:
      containers:
      - name: zookeeper
        image: zookeeper:3.8-alpine
        ports:
        - containerPort: 2181
          name: client
        env:
        - name: ZOO_MY_ID
          value: "1"
        - name: ZOO_TICK_TIME
          value: "2000"
        - name: ZOO_INIT_LIMIT
          value: "10"
        - name: ZOO_SYNC_LIMIT
          value: "5"
        - name: ZOO_MAX_CLIENT_CNXNS
          value: "60"
        volumeMounts:
        - name: zk-data
          mountPath: /data
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "echo ruok | nc localhost 2181 | grep imok"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "echo ruok | nc localhost 2181 | grep imok"
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: zk-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: hexabuilders
  labels:
    app: zookeeper
    component: pulsar
spec:
  ports:
  - port: 2181
    targetPort: 2181
    name: client
  selector:
    app: zookeeper
